# Generated by Django 6.0.4 on 2026-04-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='date',
            new_name='date_added',
        ),
    ]
